#!/bin/sh

#
# The following variable are usable:
#
# $FILES_SELECTED - The currently selected file
# $LEFT_PANE - The directory of the left pane
# $RIGHT_PANE - The directory of the right pane
# $CURRENT_DIRECTORY - The currently selected directory
# $LEFT_PANE_SELECTED_FILE - The currently selected file in the left pane
# $RIGHT_PANE_SELECTED_FILE - The currently selected file in the right pane

#
# This script will kill the server launched with the `simpleserver` script.
#
pid=`cat ~/.serverpid`
kill $pid
rm ~/.serverpid
